### ISSUE TITLE
completion not working in custom zsh setup

### ISSUE THREAD

**Issue by unmarshall** [gardener/gardenctl-v2#113]
Hello,

Thanks for reaching out so quickly and helping in identifying the issue.
**Issue:**
When you run `gardenctl rc zsh` then it will generate the following script:
```bash
if (( $+commands[gardenctl] )); then
    gctl_completion_file="${fpath[1]}/_gardenctl"
    if [[ ! -f "$gctl_completion_file" ]]; then
        gardenctl completion zsh >| "$gctl_completion_file"
        source "$gctl_completion_file"
    else
        source "$gctl_completion_file"
        gardenctl completion zsh >| "$gctl_completion_file" &|
    fi
    unset gctl_completion_file
fi
```
If your $fpath contains a location (first one) which does not exist then this `gardenctl completion zsh` will never run. This was the first finding. I had temporarily changed this script to not take the path from $fpaths and the `gardenctl completion zsh` was run and sourced. However the completion still did not work.

It was found that cobra generates the completion script which has `compdef _gardenctl gardenctl` commented out. This cause the issue on my setup of zsh and it did not run the function `_gardenctl`. However when i uncommented this line in the script it started to work.

Please check if always enabling this would not be a problem in a vanilla zsh or other setups (whichever can be tested). If its safe to do it then you can make this change in the tool, else i will continue to use a function which will explicitly call this.

Best Regards,
Madhav

**Comment by holgerkoser** [comment]
I have done fix / improvement in gardenctl-v2 which is not yet released. It should solve the problems with the zgen plugin manager or oh-my-zsh framework. I think the solution is to load the output of the command gardenctl `rc zsh --prefix <myprefix>` as a regular zsh plugin and not source it at the end of the `.zshrc` file. I have also described this in the [help](https://github.com/gardener/gardenctl-v2/blob/bug/no-config-fix/docs/help/gardenctl_rc_zsh.md#zshell-frameworks-or-plugin-manager) of the `rc` command for zsh. In your I think you have to create a custom plugin for gardenctl.

####  Create a custom zsh plugin for gardenctl
Create directory and plugin file
```sh
mkdir -p ~/.zgen/robbyrussell/oh-my-zsh-master/custom/plugins/gardenctl
cat > ~/.zgen/robbyrussell/oh-my-zsh-master/custom/plugins/gardenctl/gardenctl.plugin.zsh <<EOL
# source <(gardenctl rc zsh)
if [ -z "$GCTL_SESSION_ID" ] && [ -z "$TERM_SESSION_ID" ]; then
  export GCTL_SESSION_ID=$(uuidgen)
fi
if (( $+commands[gardenctl] )); then
  if [ -d "$ZSH_CACHE_DIR/completions" ] && (($fpath[(Ie)$ZSH_CACHE_DIR/completions])); then
    GCTL_COMPLETION_FILE="$ZSH_CACHE_DIR/completions/_gardenctl"
  else
    GCTL_COMPLETION_FILE="${fpath[1]}/_gardenctl"
  fi
  if [[ ! -f "$GCTL_COMPLETION_FILE" ]]; then
    typeset -g -A _comps
    autoload -Uz _gardenctl
    _comps[gardenctl]=_gardenctl
  fi
  gardenctl completion zsh >| "$GCTL_COMPLETION_FILE" &|
  unset GCTL_COMPLETION_FILE
fi
alias g=gardenctl
alias gtv='gardenctl target view -o yaml'
alias gtc='gardenctl target control-plane'
alias gtc-='gardenctl target unset control-plane'
alias gk='eval $(gardenctl kubectl-env zsh)'
alias gp='eval $(gardenctl provider-env zsh)'
alias gcv='gardenctl config view -o yaml' 
EOL
```
#### Load this plugin the `.zshrc` file
It should look something like this:
```sh
# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init script doesn't exist
if ! zgen saved; then

  # specify plugins here
  zgen oh-my-zsh
  ...
  zgen oh-my-zsh plugins/kubectl
  zgen load $ZSH/custom/plugins/gardenctl

  # generate the init script from plugins above
  zgen save
fi
```

#### Update the init script of `zgen` 
```sh
zgen reset
```
The next time you open a shell gardenctl aliases and completion should work without any further changes.
