### ISSUE TITLE
auto-detected system's CIDR is not correct 

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl-v2#139]
**What happened**:
auto-detected system's CIDR is not correct, then unable to ssh. 
<img width="1691" alt="image" src="https://user-images.githubusercontent.com/42234376/159616794-bc211163-8a92-4059-a6f1-4bbd5e9be0b1.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
g ssh

**Anything else we need to know**:
APJ region
**Environment**:

**Comment by tedteng** [comment]
not sure about another region, It may only happen in APJ. if is I will take a look as it easily reproduces from the APJ region

**Comment by petersutter** [comment]
Hi @tedteng, https://www.ipify.org/ is used to guess the IP. It seems like this service produces other results than whatismyipaddress.com

In case the auto detected IP does not work for you, you can provide the cidr using `--cidr` flag to override the default

**Comment by tedteng** [comment]
Thanks!  don't know this feature `--cidr `  It looks great. 
/close
