### ISSUE TITLE
when ssh hangs, gardenctl ssh command unable to exit

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl-v2#142]
**What happened**:

during the trouble shooting of a cluster, when `gardenctl ssh` command hangs after adding keys (probably due to there's sth wrong with OS), gardenctl unable to exit (by ctrl+c), the only way is to close the terminal which causing resource leakage

**What you expected to happen**:

`gardenctl ssh` is able to exit at any phase

**How to reproduce it (as minimally and precisely as possible)**:

`gardenctl ssh` a problem node
![image](https://user-images.githubusercontent.com/42594392/160309862-da8ed887-4d7f-4b88-bb97-08b61f1f07a0.png)

**Anything else we need to know**:

**Environment**:

**Comment by petersutter** [comment]
similar to https://github.com/gardener/gardenctl-v2/issues/139

you have to specify your internal ip using `--cidr` flag. The auto-detection mechanism is only a best guess

@neo-liang-sap how do you come to the conclusion that resources leaked? gardenctl creates a bastion resource and heartbeats it as long as gardenctl is running. If there is no heartbeat anymore for a certain amount of time the controller acting upon the bastion resource cleans it up.

**Comment by neo-liang-sap** [comment]
> you have to specify your internal ip using --cidr flag. 

>gardenctl creates a bastion resource and heartbeats it as long as gardenctl is running. If there is no heartbeat anymore for a certain amount of time the controller acting upon the bastion resource cleans it up.

Thanks! never know these two cool features!
/close

**Comment by neo-liang-sap** [comment]
Hi @petersutter
today i met this issue again, the cidr is correct from gardenctl-v2 but `gardenctl ssh` just hang after adding host to known hosts
/reopen

**Comment by neo-liang-sap** [comment]
![image](https://user-images.githubusercontent.com/42594392/160505429-63169969-a9e8-4d2d-b353-2788c25765d4.png)

**Comment by tedteng** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/42234376/160507827-cc1649af-1343-4479-b3fd-fa84ceb3299c.png">

The bastion host is available,  you can open additional ssh sessions using the command below,  any error coce after your using ssh command?

**Comment by neo-liang-sap** [comment]
same error in new window, hang
![image](https://user-images.githubusercontent.com/42594392/160509025-40e04565-e977-471c-b3f1-35faafe6aadb.png)

**Comment by tedteng** [comment]
can't reproduce the issue.  it looks like you are accessing one of the nodes from the AWS cloud provider, let me know if not. and can you provide the following information when the issue occurred again next time.
1) Target Cluster
2) `telnet` bastion IP 22 , the IP is shown after the message `Bastion host becomes available at xxx.xxx.xxx.xxx`", and check the IP whether reachable as well?

**Comment by neo-liang-sap** [comment]
>check the IP whether reachable as well

As the key has exchanged, definitely the bastion is reachable but unable to finish ssh login

>accessing one of the nodes from the AWS cloud provider

Yes

Will provide cluster details in private slack channel

**Comment by petersutter** [comment]
we should properly handle the signals (e.g. SIGINT) in gardenctl so that the user is not forced to terminated the shell

**Comment by petersutter** [comment]
from the man page of the `ssh` command:
```
ESCAPE CHARACTERS
     When a pseudo-terminal has been requested, ssh supports a number of functions through the use of an escape character.

     A single tilde character can be sent as ~~ or by following the tilde by a character other than those described below.  The escape character must always follow a newline to be
     interpreted as special.  The escape character can be changed in configuration files using the EscapeChar configuration directive or on the command line by the -e option.

     The supported escapes (assuming the default ‘~’) are:

     ~.      Disconnect.

     ~^Z     Background ssh.

     ~#      List forwarded connections.

     ~&      Background ssh at logout when waiting for forwarded connection / X11 sessions to terminate.

     ~?      Display a list of escape characters.

     ~B      Send a BREAK to the remote system (only useful if the peer supports it).

     ~C      Open command line.  Currently this allows the addition of port forwardings using the -L, -R and -D options (see above).  It also allows the cancellation of existing
             port-forwardings with -KL[bind_address:]port for local, -KR[bind_address:]port for remote and -KD[bind_address:]port for dynamic port-forwardings.  !command allows the
             user to execute a local command if the PermitLocalCommand option is enabled in ssh_config(5).  Basic help is available, using the -h option.

     ~R      Request rekeying of the connection (only useful if the peer supports it).

     ~V      Decrease the verbosity (LogLevel) when errors are being written to stderr.

     ~v      Increase the verbosity (LogLevel) when errors are being written to stderr.
```

so with `Enter` `~` `.` you should be able to disconnect

/close
