### ISSUE TITLE
Fallback to <shoot-name>.kubeconfig secret, if kubeconfig configmap is not found

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardenctl-v2#151]
**What would you like to be added**:

Currently, gardenctl tries to fetch the kubeconfig for a shoot cluster from a configmap named `<shoot-name>.kubeconfig` in the shoot's namespace. This leads to the following error in my case:
```
gctl target shoot gs-aws
Error: failed to get kubeconfig for shoot <shoot-namespace>/<shoot-name>: failed to get configmap <shoot-namespace>/<shoot-name>.kubeconfig: configmaps "<shoot-name>.kubeconfig" not found
```

I assume that the configmap doesn't exist yet, because the shoot cluster is stuck in creation (which is why I want to target it to SSH into the nodes).

However, there is already a secret with name `<shoot-name>.kubeconfig` in the shoot namespace, which contains the kubeconfig. I can create the configmap manually by copying the contents from this secret, but it would be much nicer if gardenctl had a kind of fallback to check for this secret, if it can't find the configmap, since there seem to be cases in which the secret exists but the configmap doesn't.

**Comment by petersutter** [comment]
we already have a fix for this which will be included in the next release https://github.com/gardener/gardenctl-v2/pull/149 
you can also clone the current repo and run (for mac) to test if it would solve your issue
```sh
make build-darwin-amd64 && chmod +x ./bin/darwin-amd64/gardenctl_v2_darwin_amd64 && mv ./bin/darwin-amd64/gardenctl_v2_darwin_amd64 /usr/local/bin/gardenctl
```

**Comment by petersutter** [comment]
> However, there is already a secret with name <shoot-name>.kubeconfig in the shoot namespace, which contains the kubeconfig. I can create the configmap manually by copying the contents from this secret, [...]

Please do not do this as the  kubeconfig contains credentials. If you would really wanted to create it by hand you would rather create a kubeconfig like this https://github.com/gardener/gardenlogin#usage
But as said, this will not be necessary with the mentioned PR
