### ISSUE TITLE
target: only target flags which higher specificity shall be available for subcommands

### ISSUE THREAD

**Issue by sven-petersen** [gardener/gardenctl-v2#195]
**What would you like to be added**:

Currently the target flags `--garden`, `--project`, `--shoot`, `--seed`, `--control-plane` are available for the `target` and all of its subcommands.

Clarify if

1) we want to keep it this way and allow sth. like `target project myproject --garden mygarden` OR
2) the target flags should only be available if none of the target-subcommand is used (`target --garden mygarden`)
**3) only target flags with a higher specificity are allowed. So `target project myproject --shoot myshoot` would be ok but not `target project myproject --garden mygarden` would not.**

**Why is this needed**:

follow up for [#85](https://github.com/gardener/gardenctl-v2/issues/85)

**Comment by petersutter** [comment]
Only target flags with lower specificity should be allowed (1.)
