### ISSUE TITLE
introduce plug-in feature in gardenctlv2  

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl-v2#299]
**What would you like to be added**:
inspired by ticket https://github.com/gardener/gardenctl-v2/issues/12 introduce plug-in feature in gardenctlv2  
**Why is this needed**:
By using the Golang plugin mechanism https://pkg.go.dev/plugin,  people can develop their own custom plugins. some less generic functions do not necessarily have to be added to the core code, in order to prevent the core functions from becoming too bloated.  meanwhile, some plugins can be designed more for internal use and internal maintenance if needs

**Comment by petersutter** [comment]
Why would we require the additional complexity of a plugin mechanism? Why isn't it sufficient to call gardenctl and consume it's output in your preferred format (json/yaml) if necessary?

**Comment by tedteng** [comment]
in fact, I am considering using extension functions to implement some customized requirements. such as implementing a simple command to combine and display the output of cloud provider information during troubleshooting for personal purposes, instead of using `aws ec2 xxx`  check one by one. or https://github.com/gardener/gardenctl-v2/pull/162 become plugins instead of in the main code. 
Anyways, as you mentioned might output the preferred format. or develop some small tools in my local is also an option.
