### ISSUE TITLE
Update Lint rules

### ISSUE THREAD

**Issue by grolu** [gardener/gardenctl-v2#45]
**What would you like to be added**:
The current lint rules that not match the errors shown in the IDE.
Moreover, there are a couple of checks that need to be added
- mssing doc string
...

**Why is this needed**:
Dev productivity

**Comment by petersutter** [comment]
<img width="2264" alt="Screenshot 2022-01-26 at 18 38 33" src="https://user-images.githubusercontent.com/5526658/151216804-cf166691-853f-431a-809c-01bb990f9843.png">
here are some linters that we could consider to enable.
However I haven't seen any as of now that reports missing doc string for exports..
